version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
        - 27017:27017
    volumes:
        - ./data:/data
  dsmarket:
    image: dsmarket
    restart: always
    container_name: dsMarket
    ports:
        - 5000:5000
    environment:
        - "MONGO_HOSTNAME=mongodb"